[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
fadroma = { version = "0.8.7", features = ["vk"] }
serde = { version = "1.0.114", default-features = false, features = ["derive"] }
